version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: mongo_db 
    ports:
      - "27017:27017"
    networks:
      - net1
      - net2
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=mid

  backend:
    build:
      context: ./Server
      dockerfile: Dockerfile
    container_name: mid_backend 
    ports:
      - "5000:5000"
    networks:
      - net1
    environment:
      - MONGO_URI=mongodb://mongo:27017/mid
      - PORT=5000
    depends_on:
      - mongo
    restart: unless-stopped

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - VITE_APP_API_URL=http://localhost:5000
    container_name: mid_frontend  
    ports:
      - "3000:80"
    networks:
      - net2
    depends_on:
      - backend
    restart: unless-stopped

networks:
  net1:
    external: true
  net2:
    external: true

volumes:
  mongo-data: